### ISSUE TITLE
People having trouble to use get the .jar file

### ISSUE THREAD

**Issue by gatemezing** [fekaputra/shacl-plugin#12]
Hi @fekaputra ,
Following a thread at the Protégé List (https://mailman.stanford.edu/pipermail/protege-user/2016-April/004153.html), I was wondering if you can provide a single .jar file and a small documentation explaining how to use the plugin? There are many people interested in using your plugin.

**Comment by x-lin** [comment]
Hi @gatemezing, the plugin is currently under development and we did encounter an issue with incompabilities regarding the Jena version that was used by [TopQuadrant's SHACL engine](https://github.com/TopQuadrant/shacl), which should be resolved by their latest commit, however I didn't have the time yet to check it out. I will try to provide a build and a short documentation by next week. Thanks for being interested in this project and I hope that answers your question.

**Comment by fekaputra** [comment]
resolved with the 0.3.0 release
