### ISSUE TITLE
Constaint Tree: error

### ISSUE THREAD

**Issue by MiXiBo** [fekaputra/shacl-plugin#15]
When loading the SHACL plugin I get an error within Protege in the constraint tree view.

An error occurred whilst creating the view ClassNotFoundException:
at.ac.tuwien.shacl.plugin.ShaclConstraintTreeViewComponent not found by at.ac.tuwien.shacl.plugin [2 1]

![screen shot 2018-09-18 at 8 16 59 pm](https://user-images.githubusercontent.com/34360898/45686910-e874a780-bb7f-11e8-9395-7099a3cb6394.png)

**Comment by poetess00** [comment]
Same issues.  Any luck?

**Comment by tdipali** [comment]
Same Issue... Any luck to get solution for this?

**Comment by obkhan** [comment]
Hi, it looks perhaps shaclconstraintreeview.java not committed to github? Could it be commented out or checked in to allow to develop further? Would be very helpful to be able get past this error

**Comment by fekaputra** [comment]
for the moment I commented this out and marked this as resolved
