### ISSUE TITLE
needs document

### ISSUE THREAD

**Issue by houzw** [fekaputra/shacl-plugin#16]
Is there any document available help me to ues this plugin?
I have found this paper SHACL4P: SHACL constraints validation within Protégé ontology editor, but I have no access to full text.

**Comment by fekaputra** [comment]
Hi, I can send you the paper if you provide me with your contact detail (e.g., via Research Gate). Currently, several users report problems with a newer version of Protege. However, I don't have time yet to work on these issues.

**Comment by houzw** [comment]
@fekaputra I have send a full-text request on Research Gate, thanks
