### ISSUE TITLE
Example file?

### ISSUE THREAD

**Issue by crapo** [fekaputra/shacl-plugin#19]
#3 in the Readme file is a bit unclear. It says, "(optional) Download the owl file from the latest release" but if I go to the latest release I see no OWL file. Is it supposed to be in the JAR file? In the Source file? Please provide a working demo use case.

**Comment by Locke** [comment]
When I wrote that sentence my intension was that the example file should be uploaded manually when a release is done to the assets section.

However, I now think that this is too much manual work and easy to forget when doing a release.

@fekaputra I can imagine different ways to solve this. One would be to link to the resources folder https://github.com/fekaputra/shacl-plugin/tree/master/src/main/resources and write in the instruction how to download the example3-data.owl file. Another option would be to directly link to https://raw.githubusercontent.com/fekaputra/shacl-plugin/master/src/main/resources/example3-data.owl or to copy the file into the root folder (which has the risk that that file could diverge from the one in the resources folder). What do you prefer?

**Comment by fekaputra** [comment]
@crapo apologize for the confusion, I'll update the readme and add a working demo use case together with our next release in a few days. 
@Locke I think it would be sufficient to have a direct link to the raw data in the README file. This way, we won't have the risk of the divergence.
